export interface JizuraColorScheme {
  bg: string
  fg: string
  sub: string
  accent: string
  accent2: string
  ink: string
  dim: string
  ghostA?: string
  ghostB?: string
}

export interface JizuraStyleDef {
  id: string
  name: string
  desc: string
  category: 'cyber' | 'retro' | 'minimal' | 'wa' | 'pop' | 'horror' | 'nature'
  scheme: JizuraColorScheme
  defaultTreatment: 'none' | 'outline' | 'doubleOutline' | 'extrude' | 'hardShadow' | 'glow' | 'marker' | 'gradientV' | 'glitchSplit' | 'boxed' | 'sticker'
  defaultLayout: 'center' | 'mixed' | 'vcols' | 'huge' | 'marquee' | 'staircase' | 'pill' | 'bubble' | 'ransom' | 'karaoke'
  defaultPreset: string
  backgroundType: string
}

/**
 * 27 种源自 JIZURA (字面) 的电影级文字 PV 风格模板预设库
 */
export const JIZURA_STYLES: JizuraStyleDef[] = [
  {
    id: 'noir',
    name: '黑白色差 · Noir',
    desc: '黑白极简基调，带青色与琥珀色 RGB 色彩错位',
    category: 'cyber',
    scheme: {
      bg: '#060607',
      fg: '#F5EEEA',
      sub: '#BDB6B2',
      accent: '#F5A50C',
      accent2: '#16F4D4',
      ink: '#F5EEEA',
      dim: '#2A2A2E',
      ghostA: '#F5A50C',
      ghostB: '#16F4D4',
    },
    defaultTreatment: 'glitchSplit',
    defaultLayout: 'mixed',
    defaultPreset: 'pop',
    backgroundType: 'dotGrid',
  },
  {
    id: 'crimson',
    name: '深红信号 · Crimson',
    desc: '深红底色、高对比黑白文字与数据故障风',
    category: 'cyber',
    scheme: {
      bg: '#C8103F',
      fg: '#FFFFFF',
      sub: '#FFD9E2',
      accent: '#140509',
      accent2: '#39F2C8',
      ink: '#140509',
      dim: '#B00D37',
      ghostA: '#FFFFFF',
      ghostB: '#39F2C8',
    },
    defaultTreatment: 'hardShadow',
    defaultLayout: 'huge',
    defaultPreset: 'slideL',
    backgroundType: 'scanBars',
  },
  {
    id: 'caution',
    name: '警示标 · Caution',
    desc: '警示黄、红黑强对比与仪表工业感',
    category: 'cyber',
    scheme: {
      bg: '#F5B700',
      fg: '#121214',
      sub: '#5E543B',
      accent: '#D91E2A',
      accent2: '#0D68D9',
      ink: '#121214',
      dim: '#D6A000',
      ghostA: '#D91E2A',
      ghostB: '#0D68D9',
    },
    defaultTreatment: 'boxed',
    defaultLayout: 'marquee',
    defaultPreset: 'drop',
    backgroundType: 'hexGrid',
  },
  {
    id: 'magenta',
    name: '波普洋红 · Magenta',
    desc: '高饱和亮粉色、圆润粗体与引线标注',
    category: 'pop',
    scheme: {
      bg: '#FF2A6D',
      fg: '#FFFFFF',
      sub: '#FFE0EB',
      accent: '#05D9E8',
      accent2: '#FEE800',
      ink: '#100018',
      dim: '#E01758',
      ghostA: '#05D9E8',
      ghostB: '#FEE800',
    },
    defaultTreatment: 'sticker',
    defaultLayout: 'pill',
    defaultPreset: 'pop',
    backgroundType: 'halftoneFade',
  },
  {
    id: 'paper',
    name: '纸与墨 · Paper & Ink',
    desc: '古典纸张质感、靛蓝洋红重影与精致排版',
    category: 'minimal',
    scheme: {
      bg: '#F0EAD6',
      fg: '#1C2333',
      sub: '#5D6B82',
      accent: '#C73E3A',
      accent2: '#2B5F8C',
      ink: '#1C2333',
      dim: '#DCD4BE',
      ghostA: '#C73E3A',
      ghostB: '#2B5F8C',
    },
    defaultTreatment: 'doubleOutline',
    defaultLayout: 'staircase',
    defaultPreset: 'riseMask',
    backgroundType: 'tornPaper',
  },
  {
    id: 'hud',
    name: '暗色 HUD · Cyberpunk',
    desc: '炭灰冷底、细线框与日食科技刻度',
    category: 'cyber',
    scheme: {
      bg: '#0D1117',
      fg: '#58A6FF',
      sub: '#8B949E',
      accent: '#FFA657',
      accent2: '#7EE787',
      ink: '#C9D1D9',
      dim: '#21262D',
      ghostA: '#58A6FF',
      ghostB: '#FFA657',
    },
    defaultTreatment: 'glow',
    defaultLayout: 'mixed',
    defaultPreset: 'spin',
    backgroundType: 'hexGrid',
  },
  {
    id: 'mint',
    name: '薄荷终端 · Terminal',
    desc: '极客黑底、青绿青柠色与控制台扫描线',
    category: 'cyber',
    scheme: {
      bg: '#050D0A',
      fg: '#16F4D4',
      sub: '#489B8F',
      accent: '#B8F416',
      accent2: '#FFFFFF',
      ink: '#16F4D4',
      dim: '#0F261F',
      ghostA: '#16F4D4',
      ghostB: '#B8F416',
    },
    defaultTreatment: 'glow',
    defaultLayout: 'center',
    defaultPreset: 'type',
    backgroundType: 'scanBars',
  },
  {
    id: 'specimen',
    name: '字体样本 · Typo Specimen',
    desc: '墨黑背景、杂志感宋体排版与排字编号',
    category: 'minimal',
    scheme: {
      bg: '#141416',
      fg: '#FFFFFF',
      sub: '#888890',
      accent: '#E63946',
      accent2: '#A8DADC',
      ink: '#F1FAEE',
      dim: '#282830',
      ghostA: '#E63946',
      ghostB: '#457B9D',
    },
    defaultTreatment: 'extrude',
    defaultLayout: 'huge',
    defaultPreset: 'slideL',
    backgroundType: 'dotGrid',
  },
  {
    id: 'transit',
    name: '交通标识 · Transit',
    desc: '橄榄绿与标识黄，路牌与导向网点',
    category: 'minimal',
    scheme: {
      bg: '#1B3B2B',
      fg: '#FFFFFF',
      sub: '#A3C4B2',
      accent: '#FFD100',
      accent2: '#FF4D4D',
      ink: '#FFFFFF',
      dim: '#2A553F',
      ghostA: '#FFD100',
      ghostB: '#FF4D4D',
    },
    defaultTreatment: 'boxed',
    defaultLayout: 'pill',
    defaultPreset: 'drop',
    backgroundType: 'dotGrid',
  },
  {
    id: 'blueprint',
    name: '工程蓝图 · Blueprint',
    desc: '经典深蓝白线，建筑图纸网格与图形拼贴',
    category: 'cyber',
    scheme: {
      bg: '#0B3C5D',
      fg: '#FFFFFF',
      sub: '#8CAEC9',
      accent: '#FCD116',
      accent2: '#328CC1',
      ink: '#FFFFFF',
      dim: '#1D2731',
      ghostA: '#FFFFFF',
      ghostB: '#FCD116',
    },
    defaultTreatment: 'outline',
    defaultLayout: 'mixed',
    defaultPreset: 'pop',
    backgroundType: 'dotGrid',
  },
  {
    id: 'rouge',
    name: '胭脂渐变 · Rouge Gradient',
    desc: '浅灰至胭脂红柔美渐变，胶囊字块',
    category: 'pop',
    scheme: {
      bg: '#25161C',
      fg: '#FFE4EC',
      sub: '#B38A98',
      accent: '#FF3366',
      accent2: '#FF99B8',
      ink: '#FFE4EC',
      dim: '#3D2530',
      ghostA: '#FF3366',
      ghostB: '#FF99B8',
    },
    defaultTreatment: 'gradientV',
    defaultLayout: 'pill',
    defaultPreset: 'blur',
    backgroundType: 'meshBlobs',
  },
  {
    id: 'mono',
    name: '单色 RGB · Mono RGB',
    desc: '中性灰阶，白字与强烈的红蓝分色重影',
    category: 'cyber',
    scheme: {
      bg: '#1A1A1E',
      fg: '#FFFFFF',
      sub: '#9E9EA8',
      accent: '#FF0055',
      accent2: '#00D9FF',
      ink: '#FFFFFF',
      dim: '#2E2E36',
      ghostA: '#FF0055',
      ghostB: '#00D9FF',
    },
    defaultTreatment: 'glitchSplit',
    defaultLayout: 'mixed',
    defaultPreset: 'slideL',
    backgroundType: 'dotGrid',
  },
  {
    id: 'sakura',
    name: '樱花和风 · Sakura',
    desc: '柔和樱粉与梅紫，浪漫唯美和风排版',
    category: 'wa',
    scheme: {
      bg: '#2A1820',
      fg: '#FEDFE6',
      sub: '#C497A4',
      accent: '#FF6B8B',
      accent2: '#E8B4B8',
      ink: '#FEDFE6',
      dim: '#472B38',
      ghostA: '#FF6B8B',
      ghostB: '#E8B4B8',
    },
    defaultTreatment: 'glow',
    defaultLayout: 'vcols',
    defaultPreset: 'riseMask',
    backgroundType: 'tornPaper',
  },
  {
    id: 'ocean',
    name: '深海流光 · Ocean Deep',
    desc: '深邃藏青、发光碧色与微光细黑体',
    category: 'nature',
    scheme: {
      bg: '#071624',
      fg: '#E0F7FA',
      sub: '#78909C',
      accent: '#00E5FF',
      accent2: '#2979FF',
      ink: '#E0F7FA',
      dim: '#0F2D4A',
      ghostA: '#00E5FF',
      ghostB: '#2979FF',
    },
    defaultTreatment: 'glow',
    defaultLayout: 'staircase',
    defaultPreset: 'blur',
    backgroundType: 'oceanWaves',
  },
  {
    id: 'sunset',
    name: '日落渐变 · Sunset Glow',
    desc: '温暖橙金至紫罗兰渐变，粗衬线与逆光',
    category: 'nature',
    scheme: {
      bg: '#1F0B24',
      fg: '#FFE082',
      sub: '#CE93D8',
      accent: '#FF7043',
      accent2: '#AB47BC',
      ink: '#FFE082',
      dim: '#3B1944',
      ghostA: '#FF7043',
      ghostB: '#AB47BC',
    },
    defaultTreatment: 'gradientV',
    defaultLayout: 'huge',
    defaultPreset: 'pop',
    backgroundType: 'sunsetSun',
  },
  {
    id: 'forest',
    name: '森林手记 · Forest Notes',
    desc: '苔绿自然纸张、铅笔手绘与森系清新',
    category: 'nature',
    scheme: {
      bg: '#1C2820',
      fg: '#E8F5E9',
      sub: '#A5D6A7',
      accent: '#C8E6C9',
      accent2: '#81C784',
      ink: '#E8F5E9',
      dim: '#2E3F33',
      ghostA: '#C8E6C9',
      ghostB: '#81C784',
    },
    defaultTreatment: 'marker',
    defaultLayout: 'mixed',
    defaultPreset: 'sway',
    backgroundType: 'tornPaper',
  },
  {
    id: 'vapor',
    name: '蒸汽波 · Vaporwave',
    desc: '马卡龙粉蓝、VHS 录像带光晕与 80s 浪漫',
    category: 'pop',
    scheme: {
      bg: '#18122B',
      fg: '#FF71CD',
      sub: '#6CD4FF',
      accent: '#FFDF78',
      accent2: '#00F5D4',
      ink: '#FFFFFF',
      dim: '#393053',
      ghostA: '#FF71CD',
      ghostB: '#6CD4FF',
    },
    defaultTreatment: 'glow',
    defaultLayout: 'pill',
    defaultPreset: 'pop',
    backgroundType: 'retroGrid',
  },
  {
    id: 'newsprint',
    name: '新闻复古纸 · Newsprint',
    desc: '做旧灰黄报纸质感，粗墨网点与红色印章',
    category: 'minimal',
    scheme: {
      bg: '#2C2B29',
      fg: '#EBE6DC',
      sub: '#A39E93',
      accent: '#D32F2F',
      accent2: '#F57C00',
      ink: '#EBE6DC',
      dim: '#474542',
      ghostA: '#D32F2F',
      ghostB: '#A39E93',
    },
    defaultTreatment: 'hardShadow',
    defaultLayout: 'staircase',
    defaultPreset: 'riseMask',
    backgroundType: 'halftoneFade',
  },
  {
    id: 'synth80',
    name: '80s 合成器 · Synthwave',
    desc: '赛博黑夜配霓虹洋红、青光地平线网格',
    category: 'cyber',
    scheme: {
      bg: '#0F051D',
      fg: '#F706CF',
      sub: '#2EF9F2',
      accent: '#FFEB3B',
      accent2: '#7B2CBF',
      ink: '#FFFFFF',
      dim: '#240046',
      ghostA: '#F706CF',
      ghostB: '#2EF9F2',
    },
    defaultTreatment: 'extrude',
    defaultLayout: 'huge',
    defaultPreset: 'pop',
    backgroundType: 'retroGrid',
  },
  {
    id: 'kraft',
    name: '牛皮纸胶带 · Kraft & Tape',
    desc: '复古暖棕纸张、红蓝印记与撕纸拼贴',
    category: 'minimal',
    scheme: {
      bg: '#2B221A',
      fg: '#F2E3D5',
      sub: '#BFA893',
      accent: '#D94336',
      accent2: '#3D7280',
      ink: '#F2E3D5',
      dim: '#47392C',
      ghostA: '#D94336',
      ghostB: '#3D7280',
    },
    defaultTreatment: 'sticker',
    defaultLayout: 'ransom',
    defaultPreset: 'sway',
    backgroundType: 'tornPaper',
  },
  {
    id: 'candy',
    name: '波普糖果 · Candy Pop',
    desc: '薄荷蓝与水果粉彩，活泼俏皮弹跳节奏',
    category: 'pop',
    scheme: {
      bg: '#1A0E2E',
      fg: '#FF6090',
      sub: '#4DEEEA',
      accent: '#FFE600',
      accent2: '#74EE15',
      ink: '#FFFFFF',
      dim: '#331B58',
      ghostA: '#FF6090',
      ghostB: '#4DEEEA',
    },
    defaultTreatment: 'doubleOutline',
    defaultLayout: 'mixed',
    defaultPreset: 'pop',
    backgroundType: 'halftoneFade',
  },
  {
    id: 'acid',
    name: '酸性朋克 · Acid Punk',
    desc: '高能荧光绿、紫红黑底与重金属张力',
    category: 'cyber',
    scheme: {
      bg: '#0A0A0C',
      fg: '#39FF14',
      sub: '#CCFF00',
      accent: '#FF007F',
      accent2: '#7928CA',
      ink: '#39FF14',
      dim: '#1F1F24',
      ghostA: '#39FF14',
      ghostB: '#FF007F',
    },
    defaultTreatment: 'glitchSplit',
    defaultLayout: 'huge',
    defaultPreset: 'spin',
    backgroundType: 'scanBars',
  },
  {
    id: 'sumi',
    name: '墨与朱 · Sumi & Vermilion',
    desc: '宣纸水墨、毛笔手书与鲜明朱砂落款',
    category: 'wa',
    scheme: {
      bg: '#141416',
      fg: '#F2EFE9',
      sub: '#949089',
      accent: '#D32F2F',
      accent2: '#E65100',
      ink: '#F2EFE9',
      dim: '#26262B',
      ghostA: '#D32F2F',
      ghostB: '#F2EFE9',
    },
    defaultTreatment: 'hardShadow',
    defaultLayout: 'vcols',
    defaultPreset: 'riseMask',
    backgroundType: 'seigaiha',
  },
  {
    id: 'gold',
    name: '金色之夜 · Golden Night',
    desc: '奢华黑金、烫金辉光与象牙衬线体',
    category: 'minimal',
    scheme: {
      bg: '#0D0D11',
      fg: '#F5D77F',
      sub: '#C5A059',
      accent: '#FFF2C6',
      accent2: '#8C6D31',
      ink: '#F5D77F',
      dim: '#1F1F29',
      ghostA: '#F5D77F',
      ghostB: '#FFF2C6',
    },
    defaultTreatment: 'glow',
    defaultLayout: 'center',
    defaultPreset: 'blur',
    backgroundType: 'meshBlobs',
  },
  {
    id: 'hrRuin',
    name: '末日废墟 · Ruin',
    desc: '褪色灰绿、锈红与回响宋体，诡异沉静',
    category: 'horror',
    scheme: {
      bg: '#0F1412',
      fg: '#A3B899',
      sub: '#5E7058',
      accent: '#9E2A2B',
      accent2: '#D4A373',
      ink: '#A3B899',
      dim: '#1E2622',
      ghostA: '#9E2A2B',
      ghostB: '#A3B899',
    },
    defaultTreatment: 'doubleOutline',
    defaultLayout: 'staircase',
    defaultPreset: 'riseMask',
    backgroundType: 'scanBars',
  },
  {
    id: 'hrNightRec',
    name: '深夜录像 · Night Rec',
    desc: '漆黑画面、监控影像白红光标与雪花噪点',
    category: 'horror',
    scheme: {
      bg: '#050505',
      fg: '#EDEDED',
      sub: '#808080',
      accent: '#FF0033',
      accent2: '#00FF66',
      ink: '#EDEDED',
      dim: '#171717',
      ghostA: '#FF0033',
      ghostB: '#EDEDED',
    },
    defaultTreatment: 'glitchSplit',
    defaultLayout: 'marquee',
    defaultPreset: 'slideL',
    backgroundType: 'scanBars',
  },
  {
    id: 'hrCurse',
    name: '暗夜密函 · Cursed Letter',
    desc: '泛黄信纸、褪色墨迹与暗红血迹笔触',
    category: 'horror',
    scheme: {
      bg: '#1A1412',
      fg: '#E6D3B3',
      sub: '#8C7764',
      accent: '#8B0000',
      accent2: '#B22222',
      ink: '#E6D3B3',
      dim: '#2E221E',
      ghostA: '#8B0000',
      ghostB: '#E6D3B3',
    },
    defaultTreatment: 'marker',
    defaultLayout: 'vcols',
    defaultPreset: 'sway',
    backgroundType: 'tornPaper',
  },
]

export function getJizuraStyles(): JizuraStyleDef[] {
  return JIZURA_STYLES
}

export function getJizuraStyle(id: string): JizuraStyleDef | undefined {
  return JIZURA_STYLES.find((s) => s.id === id)
}
